apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}
  labels:
    app: flask
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
#  - port: 443
#    protocol: TCP
#    name: https
  selector:
    app: flask
